name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Jupyter Notebook and Pandoc
        run: |
          pip install notebook
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-recommended texlive-xetex texlive-luatex pandoc-citeproc \
            texlive-latex-extra context wkhtmltopdf librsvg2-bin groff ghc nodejs \
            libjs-mathjax libjs-katex citation-style-language-styles \

      - name: Install Source Han Serif CN & Eisvogel
        run: |
          mkdir -p /tmp/SourceHanSerifCN
          wget https://mirrors.tuna.tsinghua.edu.cn/adobe-fonts/source-han-serif/SubsetOTF/SourceHanSerifCN.zip -O /tmp/SourceHanSerifCN.zip
          unzip /tmp/SourceHanSerifCN.zip -d /tmp/SourceHanSerifCN
          mkdir -p /usr/share/fonts/SourceHanSerifCN
          cp /tmp/SourceHanSerifCN/*.otf /usr/share/fonts/SourceHanSerifCN
          wget https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v2.4.1/Eisvogel-2.4.1.zip -O /tmp/Eisvogel.zip
          unzip /tmp/Eisvogel.zip -d /tmp/Eisvogel
          mkdir -p /usr/share/pandoc/data/templates/
          cp /tmp/Eisvogel/eisvogel.tex /usr/share/pandoc/data/templates/eisvogel.latex

      - name: Run build.sh
        run: ./build.sh

      - name: Upload Build Folder to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PDF & Markdown
          path: ./build